# Generated by Django 2.1.1 on 2018-09-11 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('address', models.EmailField(help_text='The addr-spec of the email as defined in RFC 5322.', max_length=254, unique=True, verbose_name='address')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='A unique identifier for the email.', primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=False, help_text='A boolean indicating if the ownership of the email has been verified.', verbose_name='is verified')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the user was created.', verbose_name='time created')),
                ('time_updated', models.DateTimeField(auto_now=True, help_text='The last time the user was edited.', verbose_name='time updated')),
                ('user', models.ForeignKey(help_text='The user who owns the email address.', on_delete=django.db.models.deletion.CASCADE, related_name='emails', related_query_name='email', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'email address',
                'verbose_name_plural': 'email addresses',
                'ordering': ('time_created',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='primary_email',
            field=models.ForeignKey(blank=True, help_text="The user's primary email address.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.Email', verbose_name='primary email address'),
        ),
    ]
