# Generated by Django 2.1.1 on 2018-09-13 17:57

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='The time the instance was created at.', verbose_name='time created')),
                ('token', models.CharField(default=account.models.random_token, editable=False, help_text='The token used to verify the associated email.', max_length=32, verbose_name='token')),
                ('email', models.ForeignKey(help_text='The email instance the verification is tied to.', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', related_query_name='verification', to='account.Email', verbose_name='email address')),
            ],
            options={
                'verbose_name': 'email verification',
                'verbose_name_plural': 'email verifications',
                'ordering': ('time_created',),
            },
        ),
    ]
