---
language: python
python: 3.6

env:
  - DJANGO_SECRET_KEY=testing

install:
  - pip install --upgrade pip
  - pip install pipenv
  - pipenv install --dev

script: pipenv run pytest api/

notifications:
  email:
    on_failure: always
    on_success: never
